### ISSUE TITLE
Getting error on sftp.get(element.name, true, 'utf8') - version 5.1.2

### ISSUE THREAD

**Issue by glintpursuit** [theophilusx/ssh2-sftp-client#224]
I am trying to read files using ssh2-sftp-client, my function use to work for node version below 10. but after updating node version to 12 getting below error for get method. I am able to get the directory list but reading file is ending up in error. 

Error : 
 `{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: wtr.once is not a function","reason":{"errorType":"TypeError","errorMessage":"wtr.once is not a function","stack":["TypeError: wtr.once is not a function","    at /var/task/node_modules/ssh2-sftp-client/src/index.js:471:15","    at new Promise (<anonymous>)","    at _get (/var/task/node_modules/ssh2-sftp-client/src/index.js:438:14)","    at SftpClient.get (/var/task/node_modules/ssh2-sftp-client/src/index.js:519:14)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)","    at async /var/task/uploadEvents.js:615:36"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: wtr.once is not a function","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:311:20)","    at process.EventEmitter.emit (domain.js:482:12)","    at processPromiseRejections (internal/process/promises.js:209:33)","    at processTicksAndRejections (internal/process/task_queues.js:98:32)"]}`

Code 

`
sftp.connect({
        host: user.url,
        port: '2222',
        username: user.userName,
        password: user.password,
        readyTimeout: 99999,
    })
        .then(() => {
            return sftp.list('/');
        })
        .then((data) => {
            var counter = data.length;
            var fullData = [];

            data.forEach(async (element) => {
                if (element.name == 'somefile.tsv') {
                  
                    var filedata = await sftp.get(element.name, true, 'utf8');

                    tsvert.setOptions({
                        indent: false,
                    });

                    try {
                        var completeStreamData = await streamToString(filedata);
                    } catch (err) {
                        console.log('# Issue while converting stream to text');
                    }

                  
                    var json = tsvJSON(completeStreamData);

                    console.log(
                        '# Complete stream data leangth ' +
                            json.length +
                            ' and filename: ' +
                            element.name
                    );

                 
                    fullData.push([element.name, json]);

                    counter--;
                    if (counter == 0) {
                        sftp.end();
                        console.log(
                            '# Connection end on reaching counter to 0'
                        );
                        callback(fullData);
                    }
                }
            });
        })
        .catch((err) => {
            console.log('# SFTP catch Error' + err + user);
            console.log('# SFTP User', user);
            callback('# SFTP catch Error' + err + user);
            sftp.end();
        });
`

**Comment by theophilusx** [comment]
> Code 
>
> ` let sftp = new Client();
>     sftp.connect({
>         host: user.url,
>         port: '2222',
>         username: user.userName,
>         password: user.password,
>         readyTimeout: 99999,
>     })
>         .then(() => {
>             return sftp.list('/');
>         })
>         .then((data) => {
>             var counter = data.length;
>             var fullData = [];
>
>             data.forEach(async (element) => {
>                 if (element.name == 'somefile.tsv') {
>                     console.log('# file name before sftp get', element.name);
>
>                     var filedata = await sftp.get(element.name, true, 'utf8');` 


You have a bug in your script. The get() method needs to be passed
either a stream object, a filename or undefined as the second argument.
You are passing 'true' which is not a valid value for that parameter.

Note that you are better off using fastGet() if all you are doing is
downloading files (and not opening them for further processing in your script).
 
from the docs

*** get(path, dst, options) ==> String|Stream|undefined

Retrieve a file from a remote SFTP server. The ~dst~ argument defines the
destination and can be either a string, a stream object or undefined. If it is a
string, it is interpreted as the path to a location on the local file system
(path should include the file name). If it is a stream object, the remote data
is passed to it via a call to pipe(). If ~dst~ is undefined, the method will put
the data into a buffer and return that buffer when the Promise is resolved. If
~dst~ is defined, it is returned when the Promise is resolved.

In general, if your going to pass in a string as the destination, you are
better off using the ~fastGet()~ method.

- path :: String. Path to the remote file to download
- dst :: String|Stream. Destination for the data. If a string, it
         should be a local file path.
- options :: Options for the ~get()~ command (see below).

**Comment by glintpursuit** [comment]
Thanks a lot @theophilusx issue got resolved :-)
